# Generated by Django 5.2.1 on 2025-10-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(choices=[('PRE_NURSERY', 'Pre-nursery'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'Junior Secondary 1 (JSS1)'), ('JSS_2', 'Junior Secondary 2 (JSS2)'), ('JSS_3', 'Junior Secondary 3 (JSS3)'), ('SS_1', 'Senior Secondary 1 (SS1)'), ('SS_2', 'Senior Secondary 2 (SS2)'), ('SS_3', 'Senior Secondary 3 (SS3)')], help_text="Select the student's current class/grade", max_length=20)),
                ('education_level', models.CharField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')], help_text='Education level category', max_length=20)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('registration_number', models.CharField(blank=True, help_text="Student's unique registration number", max_length=20, null=True, unique=True)),
                ('profile_picture', models.URLField(blank=True, help_text='Student profile picture (Cloudinary URL)', max_length=500, null=True)),
                ('classroom', models.CharField(blank=True, help_text="Specific classroom assignment (e.g., 'Primary 1 A', 'SS3 B')", max_length=50, null=True)),
                ('parent_contact', models.CharField(blank=True, help_text='Primary parent/guardian contact number', max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies', null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special educational or care requirements', null=True)),
                ('blood_group', models.CharField(blank=True, help_text="Student's blood group (e.g., A+, B-, O+)", max_length=5, null=True)),
                ('place_of_birth', models.CharField(blank=True, help_text="Student's place of birth", max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text="Student's home address", null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Student's phone number", max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Preferred payment method (e.g., Bank Transfer, Cash, etc.)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the student currently active/registered?')),
                ('stream', models.ForeignKey(blank=True, help_text='Stream assignment for Senior Secondary students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classroom.stream')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['education_level', 'student_class', 'user__first_name'],
            },
        ),
    ]
