# Generated by Django 5.2.1 on 2025-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(choices=[('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], help_text="Select the student's current class/grade", max_length=20)),
                ('education_level', models.CharField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], help_text='Education level category', max_length=10)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('parent_contact', models.CharField(blank=True, help_text='Primary parent/guardian contact number', max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies', null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special educational or care requirements', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the student currently active/registered?')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['education_level', 'student_class', 'user__first_name'],
            },
        ),
    ]
