# Generated by Django 5.2.1 on 2026-01-02 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("classroom", "0011_alter_classroomteacherassignment_classroom_and_more"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultCheckToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["education_level", "student_class"],
                name="students_st_educati_918345_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["is_active"], name="students_st_is_acti_c00e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["classroom"], name="students_st_classro_489d80_idx"
            ),
        ),
        migrations.AddField(
            model_name="resultchecktoken",
            name="school_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.term"
            ),
        ),
        migrations.AddField(
            model_name="resultchecktoken",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="resultchecktoken",
            index=models.Index(fields=["token"], name="students_re_token_76ede9_idx"),
        ),
        migrations.AddIndex(
            model_name="resultchecktoken",
            index=models.Index(
                fields=["expires_at"], name="students_re_expires_03219e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resultchecktoken",
            index=models.Index(
                fields=["is_used"], name="students_re_is_used_7d96fb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resultchecktoken",
            unique_together={("student", "school_term")},
        ),
    ]
