# Generated by Django 5.2.1 on 2025-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='student_profiles/'),
        ),
    ]
