# Generated by Django 5.2.1 on 2025-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Student profile picture (Cloudinary URL)', max_length=500, null=True),
        ),
    ]
