# Generated by Django 5.2.1 on 2025-07-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, help_text="Specific classroom assignment (e.g., 'Primary 1 A', 'SS3 B')", max_length=50, null=True),
        ),
    ]
