# Generated by Django 5.2.1 on 2025-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Student's unique registration number", max_length=20, null=True, unique=True),
        ),
    ]
