# Generated by Django 5.2.1 on 2025-08-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_stream_classroomteacherassignment_is_primary_teacher_and_more'),
        ('students', '0006_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='Stream assignment for Senior Secondary students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classroom.stream'),
        ),
    ]
