# Generated by Django 5.2.1 on 2025-08-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_update_class_names'),
        ('students', '0007_student_stream'),
    ]

    operations = [
    ]
