# Generated by Django 5.2.1 on 2025-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_merge_0002_update_class_names_0007_student_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_level',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')], help_text='Education level category', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, help_text='Primary parent/guardian contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('PRE_NURSERY', 'Pre-nursery'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'Junior Secondary 1 (JSS1)'), ('JSS_2', 'Junior Secondary 2 (JSS2)'), ('JSS_3', 'Junior Secondary 3 (JSS3)'), ('SS_1', 'Senior Secondary 1 (SS1)'), ('SS_2', 'Senior Secondary 2 (SS2)'), ('SS_3', 'Senior Secondary 3 (SS3)')], help_text="Select the student's current class/grade", max_length=20),
        ),
    ]
