# Generated by Django 5.2.1 on 2025-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text="Student's home address", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, help_text="Student's blood group (e.g., A+, B-, O+)", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Preferred payment method (e.g., Bank Transfer, Cash, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Student's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text="Student's place of birth", max_length=100, null=True),
        ),
    ]
