# Generated by Django 5.2.1 on 2025-08-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('badge_text', models.CharField(default='Special Announcement', max_length=100)),
                ('cta_text', models.CharField(default='Begin Your Journey', max_length=100)),
                ('secondary_cta_text', models.CharField(default='Watch Experience', max_length=100)),
                ('event_type', models.CharField(choices=[('announcement', 'Announcement'), ('enrollment', 'Enrollment'), ('event', 'Event'), ('achievement', 'Achievement')], default='announcement', max_length=20)),
                ('background_theme', models.CharField(choices=[('default', 'Default'), ('graduation', 'Graduation'), ('enrollment', 'Enrollment'), ('achievement', 'Achievement'), ('innovation', 'Innovation')], default='default', max_length=20)),
                ('display_type', models.CharField(choices=[('banner', 'Banner'), ('carousel', 'Carousel'), ('ribbon', 'Announcement Ribbon')], default='banner', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('ribbon_text', models.TextField(blank=True, help_text='Text to display in the announcement ribbon')),
                ('ribbon_speed', models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=20)),
                ('carousel_interval', models.IntegerField(default=5000, help_text='Auto-play interval in milliseconds')),
                ('carousel_speed', models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=20)),
                ('show_indicators', models.BooleanField(default=True)),
                ('show_controls', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
