# Generated by Django 5.2.1 on 2025-08-13 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0007_alter_studentenrollment_options_and_more'),
        ('students', '0006_student_registration_number'),
        ('subject', '0003_remove_credit_hours'),
        ('teacher', '0006_teacher_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title or topic', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed lesson description')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Lecture'), ('practical', 'Practical'), ('discussion', 'Discussion'), ('assessment', 'Assessment'), ('revision', 'Revision'), ('field_trip', 'Field Trip'), ('project', 'Project Work'), ('exam', 'Examination'), ('quiz', 'Quiz'), ('group_work', 'Group Work')], default='lecture', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of lesson completed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives')),
                ('key_concepts', models.JSONField(default=list, help_text='Key concepts to be covered')),
                ('materials_needed', models.JSONField(default=list, help_text='Required materials and resources')),
                ('assessment_criteria', models.JSONField(default=list, help_text='Assessment criteria')),
                ('teacher_notes', models.TextField(blank=True, help_text="Teacher's preparation notes")),
                ('lesson_notes', models.TextField(blank=True, help_text='Notes taken during the lesson')),
                ('student_feedback', models.TextField(blank=True, help_text='Student feedback or questions')),
                ('admin_notes', models.TextField(blank=True, help_text='Administrative notes')),
                ('attendance_count', models.PositiveIntegerField(default=0, help_text='Number of students present')),
                ('participation_score', models.PositiveIntegerField(default=0, help_text='Overall participation score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resources', models.JSONField(default=list, help_text='Links to lesson resources')),
                ('attachments', models.JSONField(default=list, help_text='File attachments')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring lesson?')),
                ('recurring_pattern', models.CharField(blank=True, help_text="Recurring pattern (e.g., 'weekly', 'daily')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_special_equipment', models.BooleanField(default=False)),
                ('is_online_lesson', models.BooleanField(default=False)),
                ('requires_substitution', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classroom.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lessons', to=settings.AUTH_USER_MODEL)),
                ('parent_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_lessons', to='lesson.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teacher.teacher')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('presentation', 'Presentation'), ('participation', 'Participation'), ('homework', 'Homework')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=100)),
                ('weight_percentage', models.PositiveIntegerField(default=10, help_text='Weight of this assessment in overall grade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='lesson.lesson')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], default='present', max_length=10)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'External Link'), ('image', 'Image'), ('presentation', 'Presentation')], max_length=15)),
                ('url', models.URLField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='lesson.lesson')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time'], name='lesson_less_date_c6cad9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date'], name='lesson_less_teacher_3755d9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['classroom', 'date'], name='lesson_less_classro_7f64ef_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lesson_less_status_faff9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('classroom', 'date', 'start_time', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonattendance',
            unique_together={('lesson', 'student')},
        ),
    ]
