# Generated by Django 5.2.1 on 2025-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='data_retention_expires_at',
            field=models.DateTimeField(blank=True, help_text='When lesson data should be cleaned up', null=True),
        ),
    ]
