# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=True)),
                ('is_present', models.BooleanField(default=False)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_description', models.TextField(blank=True)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'exams_registration',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('results_publication_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_late_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Mark this as the default exam schedule for new exams')),
            ],
            options={
                'db_table': 'exams_schedule',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('total_appeared', models.PositiveIntegerField(default=0)),
                ('total_absent', models.PositiveIntegerField(default=0)),
                ('highest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lowest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('median_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade_a_count', models.PositiveIntegerField(default=0)),
                ('grade_b_count', models.PositiveIntegerField(default=0)),
                ('grade_c_count', models.PositiveIntegerField(default=0)),
                ('grade_d_count', models.PositiveIntegerField(default=0)),
                ('grade_e_count', models.PositiveIntegerField(default=0)),
                ('grade_f_count', models.PositiveIntegerField(default=0)),
                ('total_passed', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams_statistics',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Class Test'), ('mid_term', 'Mid-Term Examination'), ('final_exam', 'Final Examination'), ('practical', 'Practical Examination'), ('oral_exam', 'Oral Examination')], default='final_exam', max_length=25)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=10)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('materials_allowed', models.TextField(blank=True)),
                ('materials_provided', models.TextField(blank=True)),
                ('questions_file', models.FileField(blank=True, null=True, upload_to='exam_questions/')),
                ('answer_key', models.FileField(blank=True, null=True, upload_to='exam_answers/')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=15)),
                ('is_practical', models.BooleanField(default=False)),
                ('requires_computer', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.gradelevel')),
            ],
            options={
                'db_table': 'exams_exam',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
    ]
