# Generated by Django 5.2.1 on 2025-06-29 02:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('classroom', '0002_academicyear_student_alter_gradelevel_options_and_more'),
        ('exam', '0001_initial'),
        ('students', '0003_alter_student_options_student_education_level_and_more'),
        ('teacher', '0003_teacher_date_of_birth_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['exam_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='exam',
            name='answer_key',
            field=models.FileField(blank=True, null=True, upload_to='exam_answers/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Class Test'), ('mid_term', 'Mid-Term Examination'), ('final_exam', 'Final Examination'), ('practical', 'Practical Examination'), ('oral_exam', 'Oral Examination')], default='final_exam', max_length=25),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='invigilated_exams', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='materials_allowed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='materials_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_questions/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='requires_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=15),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='exam',
            table='exams_exam',
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=True)),
                ('is_present', models.BooleanField(default=False)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_description', models.TextField(blank=True)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'exams_registration',
                'ordering': ['id'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('results_publication_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_late_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'db_table': 'exams_schedule',
                'ordering': ['-start_date'],
                'unique_together': {('academic_session', 'term', 'name')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.examschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'grade_level', 'section', 'exam_type', 'exam_schedule')},
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('total_appeared', models.PositiveIntegerField(default=0)),
                ('total_absent', models.PositiveIntegerField(default=0)),
                ('highest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lowest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('median_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade_a_count', models.PositiveIntegerField(default=0)),
                ('grade_b_count', models.PositiveIntegerField(default=0)),
                ('grade_c_count', models.PositiveIntegerField(default=0)),
                ('grade_d_count', models.PositiveIntegerField(default=0)),
                ('grade_e_count', models.PositiveIntegerField(default=0)),
                ('grade_f_count', models.PositiveIntegerField(default=0)),
                ('total_passed', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='exam.exam')),
            ],
            options={
                'db_table': 'exams_statistics',
            },
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
