# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.db.models.deletion
import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('classroom', '0002_initial'),
        ('exam', '0001_initial'),
        ('students', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='invigilated_exams', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_schedule',
            field=models.ForeignKey(default=exam.models.get_default_exam_schedule_id, help_text='Exam schedule this exam belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.examschedule'),
        ),
        migrations.AddField(
            model_name='examstatistics',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='exam.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='examregistration',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('academic_session', 'term', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'grade_level', 'section', 'exam_type', 'exam_schedule')},
        ),
    ]
