# Generated by Django 5.2.1 on 2025-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
