# Generated by Django 5.2.1 on 2025-06-29 04:38

import django.db.models.deletion
import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_options_exam_answer_key_exam_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this as the default exam schedule for new exams'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_schedule',
            field=models.ForeignKey(default=exam.models.get_default_exam_schedule_id, help_text='Exam schedule this exam belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.examschedule'),
        ),
    ]
