# Generated by Django 5.2.1 on 2025-08-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_stream_classroomteacherassignment_is_primary_teacher_and_more'),
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='Stream for Senior Secondary exams (Science, Arts, Commercial, Technical)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classroom.stream'),
        ),
    ]
