# Generated by Django 5.2.1 on 2025-08-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_stream_classroomteacherassignment_is_primary_teacher_and_more'),
        ('exam', '0003_exam_stream'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.section'),
        ),
    ]
