# Generated by Django 5.2.1 on 2025-08-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_unique_together_alter_exam_section'),
        ('subject', '0005_subject_compatible_streams_subject_elective_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, help_text='Exam schedule this exam belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.examschedule'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
