# Generated by Django 5.2.1 on 2025-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_exam_schedule_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='custom_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='objective_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='objective_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='practical_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='practical_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='theory_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='theory_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
