# Generated by Django 5.2.1 on 2025-09-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exam_custom_sections_exam_objective_instructions_and_more'),
        ('teacher', '0008_remove_old_teacher_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver'),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Teacher who approved this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exams', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
