# Generated by Django 5.2.1 on 2025-06-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_teacher_date_of_birth_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'db_table': 'academics_session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject_type', models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective Subject'), ('PRACTICAL', 'Practical Subject'), ('LANGUAGE', 'Language Subject'), ('VOCATIONAL', 'Vocational Subject')], default='CORE', max_length=20)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('has_practical', models.BooleanField(default=False)),
                ('credit_units', models.PositiveIntegerField(default=1)),
                ('education_levels', models.CharField(blank=True, help_text="Comma-separated education levels (e.g., 'NURSERY,PRIMARY')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'academics_subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'db_table': 'academics_curriculum',
                'ordering': ['education_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('minimum_score', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Weight in overall computation', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.curriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.subject')),
            ],
            options={
                'db_table': 'academics_curriculum_subject',
                'ordering': ['curriculum', 'order', 'subject__name'],
                'unique_together': {('curriculum', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(related_name='curricula', through='academics.CurriculumSubject', to='academics.subject'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FIRST', 'First Term'), ('SECOND', 'Second Term'), ('THIRD', 'Third Term')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('next_term_begins', models.DateField(blank=True, null=True)),
                ('holidays_start', models.DateField(blank=True, null=True)),
                ('holidays_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'db_table': 'academics_term',
                'ordering': ['academic_session', 'name'],
                'unique_together': {('academic_session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('TERM_START', 'Term Start'), ('TERM_END', 'Term End'), ('HOLIDAY', 'Holiday'), ('EXAM', 'Examination'), ('REGISTRATION', 'Student Registration'), ('GRADUATION', 'Graduation'), ('ORIENTATION', 'Orientation'), ('SPORTS', 'Sports Event'), ('CULTURAL', 'Cultural Event'), ('MEETING', 'Academic Meeting'), ('OTHER', 'Other Event')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.academicsession')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.term')),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'verbose_name_plural': 'Academic Calendar Events',
                'db_table': 'academics_calendar',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'education_level', 'academic_session')},
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=50)),
                ('periods_per_week', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Subject Allocation',
                'verbose_name_plural': 'Subject Allocations',
                'db_table': 'academics_subject_allocation',
                'ordering': ['academic_session', 'education_level', 'student_class', 'subject'],
                'unique_together': {('subject', 'teacher', 'academic_session', 'education_level', 'student_class')},
            },
        ),
    ]
