# Generated by Django 5.2.1 on 2025-10-09 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(related_name='curricula', through='academics.CurriculumSubject', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('curriculum', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'education_level', 'academic_session')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('subject', 'teacher', 'academic_session', 'education_level', 'student_class')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_session', 'name')},
        ),
    ]
