# Generated by Django 5.2.1 on 2025-08-31 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fee', '0005_academicsession_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='fee.academicsession'),
        ),
    ]
