# Generated by Django 5.2.1 on 2025-10-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(related_name='curricula', through='academics.CurriculumSubject', to='subject.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
