# Generated by Django 5.2.1 on 2025-08-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_term_academic_session'),
        ('fee', '0005_academicsession_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='fee.academicsession'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='fee.academicsession'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='fee.academicsession'),
        ),
    ]
