# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Main class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_classes', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='assigned_classes', through='classroom.ClassroomTeacherAssignment', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('education_level', 'order')},
        ),
        migrations.AddField(
            model_name='section',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classroom.gradelevel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classroom.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', through='classroom.StudentEnrollment', to='classroom.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.ManyToManyField(related_name='classroom_subjects', to='classroom.gradelevel'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject'),
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='classroom.academicyear'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classroom.term'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('classroom', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomteacherassignment',
            unique_together={('classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('section', 'academic_year', 'term')},
        ),
    ]
