# Generated by Django 5.2.1 on 2025-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='education_level',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')], max_length=20),
        ),
    ]
