# Generated by Django 5.2.1 on 2025-10-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('classroom', '0003_fix_academic_session_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['classroom', 'student__user__first_name', 'student__user__last_name']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='academic_session',
            field=models.ForeignKey(help_text='Academic session this classroom belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='term',
            field=models.ForeignKey(help_text='Term within the academic session', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.term'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
