# Generated by Django 5.2.1 on 2025-10-10 16:16

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_delete_student_alter_studentenrollment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="academic_session",
            field=models.ForeignKey(
                help_text="Academic session this classroom belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.academicsession",  # This is the key change
            ),
        ),
    ]
