# Generated by Django 5.2.1 on 2025-08-12 14:19

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_classroomteacherassignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomteacherassignment',
            name='assigned_date',
            field=models.DateField(default=classroom.models.get_current_date),
        ),
    ]
