# Generated by Django 5.2.1 on 2025-08-12 14:20

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_classroomteacherassignment_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=classroom.models.get_current_date),
        ),
    ]
