# Generated by Django 5.2.1 on 2025-10-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20251010_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gradelevel',
            table='classroom_gradelevely',
        ),
    ]
