# Generated by Django 5.2.1 on 2025-10-14 07:59

from django.db import migrations


def move_stream_to_students(apps, schema_editor):
    """Move classroom stream to student stream for SS students"""
    Classroom = apps.get_model("classroom", "Classroom")
    StudentEnrollment = apps.get_model("classroom", "StudentEnrollment")
    Student = apps.get_model("students", "Student")

    for classroom in Classroom.objects.filter(stream__isnull=False):
        # Get all students enrolled in this classroom
        enrollments = StudentEnrollment.objects.filter(
            classroom=classroom, is_active=True
        ).select_related("student")

        for enrollment in enrollments:
            # Assign the classroom's stream to the student if not already set
            if enrollment.student.stream_id is None:
                enrollment.student.stream_id = classroom.stream_id
                enrollment.student.save()
                print(f"Assigned stream {classroom.stream_id} to {enrollment.student}")


def reverse_move_stream(apps, schema_editor):
    # This is a one-way migration - we're not removing from students
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0006_alter_gradelevel_table"),
    ]

    operations = [
        migrations.RunPython(move_stream_to_students, reverse_move_stream),
    ]
