# Generated by Django 5.2.1 on 2025-08-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_studentenrollment_enrollment_date'),
        ('students', '0006_student_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['classroom', 'student__user__first_name']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', through='classroom.StudentEnrollment', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
