# Generated by Django 5.2.1 on 2025-08-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_studentenrollment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('stream_type', models.CharField(choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCIAL', 'Commercial'), ('TECHNICAL', 'Technical')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stream_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='is_primary_teacher',
            field=models.BooleanField(default=False, help_text='Whether this teacher is the primary teacher for this subject in this classroom'),
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='periods_per_week',
            field=models.PositiveIntegerField(default=1, help_text='Number of periods per week for this subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='Stream for Senior Secondary classes (Science, Arts, Commercial, Technical)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='classroom.stream'),
        ),
    ]
