# Generated by Django 5.2.1 on 2025-10-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('classroom', '0007_move_stream_to_students'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('section', 'academic_session', 'term', 'name')},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='stream',
        ),
    ]
