# Generated by Django 5.2.1 on 2025-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_classroom_unique_together_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects taught in this classroom (mainly for Nursery & Primary)', related_name='classrooms', to='subject.subject'),
        ),
    ]
