# Generated by Django 5.2.1 on 2025-12-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0009_classroom_subjects"),
        ("subject", "0001_initial"),
        (
            "teacher",
            "0002_rename_academic_year_teacherschedule_academic_session_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomteacherassignment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="classroom.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="classroomteacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_assignments",
                to="subject.subject",
            ),
        ),
        migrations.AlterField(
            model_name="classroomteacherassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_assignments",
                to="teacher.teacher",
            ),
        ),
    ]
