# Generated by Django 5.2.1 on 2025-12-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0010_alter_classroomteacherassignment_classroom_and_more"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomteacherassignment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classroom.classroom"
            ),
        ),
        migrations.AlterField(
            model_name="classroomteacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subject.subject"
            ),
        ),
    ]
