# Generated by Django 5.2.1 on 2025-10-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subjectallocation_subject_and_more'),
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscount',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.DeleteModel(
            name='AcademicSession',
        ),
    ]
