# Generated by Django 5.2.1 on 2025-07-31 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attempt_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ABANDONED', 'Abandoned'), ('REFUNDED', 'Refunded')], max_length=15)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual Payment')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_installments', models.IntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual Payment')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feediscount',
            options={'ordering': ['name'], 'verbose_name': 'Fee Discount', 'verbose_name_plural': 'Fee Discounts'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['name'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AlterModelOptions(
            name='paymentreminder',
            options={'ordering': ['-sent_date'], 'verbose_name': 'Payment Reminder', 'verbose_name_plural': 'Payment Reminders'},
        ),
        migrations.AlterModelOptions(
            name='studentdiscount',
            options={'verbose_name': 'Student Discount', 'verbose_name_plural': 'Student Discounts'},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Fee', 'verbose_name_plural': 'Student Fees'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paystack_reference',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paystack_status',
            new_name='card_type',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paystack_transaction_id',
            new_name='gateway_reference',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ABANDONED', 'Abandoned'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual Payment')], default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='feediscount',
            name='applicable_fee_types',
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], max_length=15),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='education_level',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='student_class',
            field=models.CharField(choices=[('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('PRE_K', 'Pre-K'), ('KINDERGARTEN', 'Kindergarten'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK_CARD', 'Paystack - Card Payment'), ('PAYSTACK_BANK', 'Paystack - Bank Transfer'), ('FLUTTERWAVE_CARD', 'Flutterwave - Card Payment'), ('FLUTTERWAVE_BANK', 'Flutterwave - Bank Transfer'), ('FLUTTERWAVE_MOBILE', 'Flutterwave - Mobile Money'), ('STRIPE_CARD', 'Stripe - Card Payment'), ('STRIPE_BANK', 'Stripe - Bank Transfer'), ('BANK_TRANSFER', 'Direct Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='reminder_type',
            field=models.CharField(choices=[('DUE_DATE', 'Due Date Reminder'), ('OVERDUE', 'Overdue Reminder'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdiscount',
            name='applied_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='term',
            field=models.CharField(choices=[('FIRST', 'First Term'), ('SECOND', 'Second Term'), ('THIRD', 'Third Term')], default='First Term', max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_reference'], name='fee_payment_gateway_c4a309_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_gateway', 'gateway_status'], name='fee_payment_payment_fd753a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student_fee', 'verified'], name='fee_payment_student_0df3a0_idx'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='fee.payment'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='fee.studentfee'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.payment'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='fee.studentfee'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fee.paymentplan'),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.payment'),
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='due_date_offset',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='late_fee_percentage',
        ),
        migrations.AddField(
            model_name='feediscount',
            name='applicable_fee_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together={('payment_plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway', 'event_type'], name='fee_payment_gateway_ba972a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['processed', 'created_at'], name='fee_payment_process_d89412_idx'),
        ),
    ]
