# Generated by Django 5.2.1 on 2025-08-18 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_paymentattempt_paymentgatewayconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
