# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Nigerian phone number format: +234XXXXXXXXXX', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g., +234XXXXXXXXXX).', regex='^\\+?234\\d{10}$')])),
                ('address', models.TextField(blank=True, help_text='Full address including city and state', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (recommended size: 300x300px)', null=True, upload_to='profile_pics/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself (max 500 characters)', max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Your date of birth (YYYY-MM-DD)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Your Twitter profile URL', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Your Facebook profile URL', null=True)),
                ('is_profile_public', models.BooleanField(default=True, help_text='Make your profile visible to other users')),
                ('receive_notifications', models.BooleanField(default=True, help_text='Receive email notifications for important updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
