# Generated by Django 5.2.1 on 2025-07-11 01:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_options_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address including city and state', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth (YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Your Facebook profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='Make your profile visible to other users'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nigerian phone number format: +234XXXXXXXXXX', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g., +234XXXXXXXXXX).', regex='^\\+?234\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (recommended size: 300x300px)', null=True, upload_to='profile_pics/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for important updates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
