# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH101, ENG201)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the subject')),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('vocational', 'Vocational Subject'), ('extra_curricular', 'Extra-Curricular'), ('language', 'Language'), ('science', 'Science'), ('mathematics', 'Mathematics'), ('social_studies', 'Social Studies'), ('arts', 'Arts'), ('physical_education', 'Physical Education'), ('religious_studies', 'Religious Studies'), ('computer_science', 'Computer Science')], default='core', help_text='Subject category for organization', max_length=20)),
                ('education_levels', models.JSONField(default=list, help_text='Education levels this subject applies to (NURSERY, PRIMARY, SECONDARY)')),
                ('credit_hours', models.PositiveIntegerField(default=1, help_text='Number of credit hours for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_compulsory', models.BooleanField(default=True, help_text='Is this subject mandatory for students?')),
                ('is_core', models.BooleanField(default=False, help_text='Core subject for all students (legacy compatibility)')),
                ('has_continuous_assessment', models.BooleanField(default=True, help_text='Does this subject have continuous assessment?')),
                ('has_final_exam', models.BooleanField(default=True, help_text='Does this subject have a final examination?')),
                ('pass_mark', models.PositiveIntegerField(default=50, help_text='Minimum pass mark percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('has_practical', models.BooleanField(default=False, help_text='Does this subject have practical components?')),
                ('practical_hours', models.PositiveIntegerField(default=0, help_text='Number of practical hours per week')),
                ('requires_lab', models.BooleanField(default=False, help_text='Does this subject require laboratory facilities?')),
                ('requires_special_equipment', models.BooleanField(default=False, help_text='Does this subject require special equipment?')),
                ('equipment_notes', models.TextField(blank=True, help_text='Notes about required equipment or facilities')),
                ('is_active', models.BooleanField(default=True, help_text='Is this subject currently being offered?')),
                ('is_discontinued', models.BooleanField(default=False, help_text='Is this subject discontinued but kept for historical records?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduced_year', models.PositiveIntegerField(blank=True, help_text='Year this subject was introduced', null=True)),
                ('grade_levels', models.ManyToManyField(help_text='Grade levels where this subject is taught', related_name='subjects', to='classroom.gradelevel')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Subjects required before taking this subject', related_name='unlocks_subjects', to='subject.subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='subject_sub_categor_d965be_idx'), models.Index(fields=['is_compulsory', 'is_active'], name='subject_sub_is_comp_0ea0b8_idx')],
            },
        ),
    ]
