# Generated by Django 5.2.1 on 2025-10-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStreamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(default=1, help_text='School ID (default: 1 for single-school systems)')),
                ('subject_role', models.CharField(choices=[('core', 'Core Subjects'), ('elective', 'Elective Subjects'), ('cross_cutting', 'Cross-Cutting Subjects')], help_text='Role of subjects in this stream', max_length=20)),
                ('min_subjects_required', models.PositiveIntegerField(default=1, help_text='Minimum number of subjects required from this category')),
                ('max_subjects_allowed', models.PositiveIntegerField(default=5, help_text='Maximum number of subjects allowed from this category')),
                ('is_compulsory', models.BooleanField(default=True, help_text='Whether students must take subjects from this category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order for this configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_configurations', to='classroom.stream')),
            ],
            options={
                'verbose_name': 'School Stream Configuration',
                'verbose_name_plural': 'School Stream Configurations',
                'ordering': ['school_id', 'stream', 'display_order'],
                'unique_together': {('school_id', 'stream', 'subject_role')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full subject name (e.g., 'Basic Science and Technology')", max_length=100)),
                ('short_name', models.CharField(blank=True, help_text="Abbreviated name for display (e.g., 'Basic Science')", max_length=50)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH-NUR, ENG-PRI, PHY-SS)', max_length=15, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the subject content and objectives')),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('cross_cutting', 'Cross Cutting Subject'), ('core_science', 'Core Science'), ('core_art', 'Core Art'), ('core_humanities', 'Core Humanities'), ('vocational', 'Vocational/Pre-vocational'), ('creative_arts', 'Cultural & Creative Arts'), ('religious', 'Religious Studies'), ('physical', 'Physical & Health Education'), ('language', 'Language'), ('practical', 'Practical/Skills'), ('nursery_activities', 'Nursery Activities')], default='core', help_text='Subject category for organization', max_length=25)),
                ('education_levels', models.JSONField(default=list, help_text='Education levels this subject applies to (NURSERY, PRIMARY, JUNIOR_SECONDARY, SENIOR_SECONDARY)')),
                ('nursery_levels', models.JSONField(blank=True, default=list, help_text='Specific nursery levels (PRE_NURSERY, NURSERY_1, NURSERY_2)')),
                ('ss_subject_type', models.CharField(blank=True, choices=[('cross_cutting', 'Cross Cutting'), ('core_science', 'Core Science'), ('core_art', 'Core Art'), ('core_humanities', 'Core Humanities'), ('elective', 'Elective')], help_text='Classification for Senior Secondary subjects', max_length=20, null=True)),
                ('is_cross_cutting', models.BooleanField(default=False, help_text='Whether this subject is cross-cutting across all streams (legacy field)')),
                ('default_stream_role', models.CharField(blank=True, choices=[('core', 'Core Subjects'), ('elective', 'Elective Subjects'), ('cross_cutting', 'Cross-Cutting Subjects')], help_text='Default role if not specifically configured by school (legacy field)', max_length=20, null=True)),
                ('subject_order', models.PositiveIntegerField(default=0, help_text='Order for display in lists')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_levels', models.ManyToManyField(blank=True, help_text='Specific grade levels where this subject is taught', related_name='subjects', to='classroom.gradelevel')),
                ('parent_subject', models.ForeignKey(blank=True, help_text='Parent subject if this is a component subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_subjects', to='subject.subject')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Subjects that must be completed before this one', related_name='unlocks_subjects', to='subject.subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['education_levels', 'category', 'subject_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStreamSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False, help_text='Whether this specific subject is compulsory')),
                ('credit_weight', models.PositiveIntegerField(default=1, help_text='Credit weight for this subject in the stream')),
                ('can_be_elective_elsewhere', models.BooleanField(default=True, help_text='Whether this subject can be taken as elective in other streams')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='subject.schoolstreamconfiguration')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Subjects that must be completed before this one', related_name='stream_assignment_prerequisites', to='subject.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='subject.subject')),
            ],
            options={
                'verbose_name': 'Stream Subject Assignment',
                'verbose_name_plural': 'Stream Subject Assignments',
                'ordering': ['stream_config', 'subject__name'],
                'unique_together': {('stream_config', 'subject')},
            },
        ),
    ]
