# Generated by Django 5.2.1 on 2025-06-29 01:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_academicyear_student_alter_gradelevel_options_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('vocational', 'Vocational Subject'), ('extra_curricular', 'Extra-Curricular'), ('language', 'Language'), ('science', 'Science'), ('mathematics', 'Mathematics'), ('social_studies', 'Social Studies'), ('arts', 'Arts'), ('physical_education', 'Physical Education'), ('religious_studies', 'Religious Studies'), ('computer_science', 'Computer Science')], default='core', help_text='Subject category for organization', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveIntegerField(default=1, help_text='Number of credit hours for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_levels',
            field=models.JSONField(default=list, help_text='Education levels this subject applies to (NURSERY, PRIMARY, SECONDARY)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='equipment_notes',
            field=models.TextField(blank=True, help_text='Notes about required equipment or facilities'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.ManyToManyField(help_text='Grade levels where this subject is taught', related_name='subjects', to='classroom.gradelevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_continuous_assessment',
            field=models.BooleanField(default=True, help_text='Does this subject have continuous assessment?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_final_exam',
            field=models.BooleanField(default=True, help_text='Does this subject have a final examination?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_practical',
            field=models.BooleanField(default=False, help_text='Does this subject have practical components?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='introduced_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year this subject was introduced', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this subject currently being offered?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Is this subject mandatory for students?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Core subject for all students (legacy compatibility)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Is this subject discontinued but kept for historical records?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.PositiveIntegerField(default=50, help_text='Minimum pass mark percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_hours',
            field=models.PositiveIntegerField(default=0, help_text='Number of practical hours per week'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Subjects required before taking this subject', related_name='unlocks_subjects', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='requires_lab',
            field=models.BooleanField(default=False, help_text='Does this subject require laboratory facilities?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='requires_special_equipment',
            field=models.BooleanField(default=False, help_text='Does this subject require special equipment?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Unique subject code (e.g., MATH101, ENG201)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category', 'is_active'], name='subject_sub_categor_d965be_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_compulsory', 'is_active'], name='subject_sub_is_comp_0ea0b8_idx'),
        ),
    ]
