# Generated by Django 5.2.1 on 2025-07-30 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['education_levels', 'category', 'subject_order', 'name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum_version',
            field=models.CharField(blank=True, help_text="Curriculum version (e.g., '2022 Curriculum')", max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_activity_based',
            field=models.BooleanField(default=False, help_text='Activity-based subject (for nursery level)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_cross_cutting',
            field=models.BooleanField(default=False, help_text='Cross-cutting subject required for all SS students'),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Key learning outcomes for this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='nursery_levels',
            field=models.JSONField(blank=True, default=list, help_text='Specific nursery levels (PRE_NURSERY, NURSERY_1, NURSERY_2)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='requires_specialist_teacher',
            field=models.BooleanField(default=False, help_text='Requires a subject specialist teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, help_text="Abbreviated name for display (e.g., 'Basic Science')", max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='ss_subject_type',
            field=models.CharField(blank=True, choices=[('cross_cutting', 'Cross Cutting'), ('core_science', 'Core Science'), ('core_art', 'Core Art'), ('core_humanities', 'Core Humanities'), ('elective', 'Elective')], help_text='Classification for Senior Secondary subjects', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying subjects within a category'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('cross_cutting', 'Cross Cutting Subject'), ('core_science', 'Core Science'), ('core_art', 'Core Art'), ('core_humanities', 'Core Humanities'), ('vocational', 'Vocational/Pre-vocational'), ('creative_arts', 'Cultural & Creative Arts'), ('religious', 'Religious Studies'), ('physical', 'Physical & Health Education'), ('language', 'Language'), ('practical', 'Practical/Skills'), ('nursery_activities', 'Nursery Activities')], default='core', help_text='Subject category for organization', max_length=25),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Unique subject code (e.g., MATH-NUR, ENG-PRI, PHY-SS)', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveIntegerField(default=1, help_text='Number of credit hours per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the subject content and objectives'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='education_levels',
            field=models.JSONField(default=list, help_text='Education levels this subject applies to (NURSERY, PRIMARY, JUNIOR_SECONDARY, SENIOR_SECONDARY)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, help_text='Specific grade levels where this subject is taught', related_name='subjects', to='classroom.gradelevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Core subject for all students'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text="Full subject name (e.g., 'Basic Science and Technology')", max_length=100),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['education_levels'], name='subject_sub_educati_ab814a_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['ss_subject_type'], name='subject_sub_ss_subj_14bc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_cross_cutting'], name='subject_sub_is_cros_7c2dae_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'education_levels'), name='unique_subject_per_education_level'),
        ),
    ]
