# Generated by Django 5.2.1 on 2025-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_options_subject_curriculum_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credit_hours',
        ),
    ]
