# Generated by Django 5.2.1 on 2025-08-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, help_text='Parent subject for component subjects (e.g., Basic Science and Technology for Basic Science)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_subjects', to='subject.subject'),
        ),
    ]
