# Generated by Django 5.2.1 on 2025-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_stream_classroomteacherassignment_is_primary_teacher_and_more'),
        ('subject', '0004_subject_parent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='compatible_streams',
            field=models.ManyToManyField(blank=True, help_text='Streams where this subject is available (for Senior Secondary)', related_name='subjects', to='classroom.stream'),
        ),
        migrations.AddField(
            model_name='subject',
            name='elective_group',
            field=models.CharField(blank=True, help_text="Group for elective subjects (e.g., 'Group A', 'Group B')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Whether this is an elective subject (students can choose)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_electives_allowed',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of electives allowed from this group'),
        ),
        migrations.AddField(
            model_name='subject',
            name='min_electives_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of electives required from this group'),
        ),
    ]
