# Generated by Django 5.2.1 on 2025-09-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_stream_classroomteacherassignment_is_primary_teacher_and_more'),
        ('subject', '0005_subject_compatible_streams_subject_elective_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStreamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(default=1, help_text='School ID (default: 1 for single-school systems)')),
                ('subject_role', models.CharField(choices=[('core', 'Core Subjects'), ('elective', 'Elective Subjects'), ('cross_cutting', 'Cross-Cutting Subjects')], help_text='Role of subjects in this stream', max_length=20)),
                ('min_subjects_required', models.PositiveIntegerField(default=1, help_text='Minimum number of subjects required from this category')),
                ('max_subjects_allowed', models.PositiveIntegerField(default=5, help_text='Maximum number of subjects allowed from this category')),
                ('is_compulsory', models.BooleanField(default=True, help_text='Whether students must take subjects from this category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order for this configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Stream Configuration',
                'verbose_name_plural': 'School Stream Configurations',
                'ordering': ['school_id', 'stream', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStreamSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False, help_text='Whether this specific subject is compulsory')),
                ('credit_weight', models.PositiveIntegerField(default=1, help_text='Credit weight for this subject in the stream')),
                ('can_be_elective_elsewhere', models.BooleanField(default=True, help_text='Whether this subject can be taken as elective in other streams')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stream Subject Assignment',
                'verbose_name_plural': 'Stream Subject Assignments',
                'ordering': ['stream_config', 'subject__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_per_education_level',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_sub_categor_d965be_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_sub_is_comp_0ea0b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_sub_educati_ab814a_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_sub_ss_subj_14bc6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_sub_is_cros_7c2dae_idx',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='compatible_streams',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='curriculum_version',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='elective_group',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='equipment_notes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='has_continuous_assessment',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='has_final_exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='has_practical',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='introduced_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_activity_based',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_compulsory',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_core',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_discontinued',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='max_electives_allowed',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='min_electives_required',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_hours',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='requires_lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='requires_special_equipment',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='requires_specialist_teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='default_stream_role',
            field=models.CharField(blank=True, choices=[('core', 'Core Subjects'), ('elective', 'Elective Subjects'), ('cross_cutting', 'Cross-Cutting Subjects')], help_text='Default role if not specifically configured by school (legacy field)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_cross_cutting',
            field=models.BooleanField(default=False, help_text='Whether this subject is cross-cutting across all streams (legacy field)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, help_text='Parent subject if this is a component subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_subjects', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Subjects that must be completed before this one', related_name='unlocks_subjects', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display in lists'),
        ),
        migrations.AddField(
            model_name='schoolstreamconfiguration',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_configurations', to='classroom.stream'),
        ),
        migrations.AddField(
            model_name='schoolstreamsubjectassignment',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Subjects that must be completed before this one', related_name='stream_assignment_prerequisites', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='schoolstreamsubjectassignment',
            name='stream_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='subject.schoolstreamconfiguration'),
        ),
        migrations.AddField(
            model_name='schoolstreamsubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='subject.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolstreamconfiguration',
            unique_together={('school_id', 'stream', 'subject_role')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolstreamsubjectassignment',
            unique_together={('stream_config', 'subject')},
        ),
    ]
