# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentstudentrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parentprofile'),
        ),
        migrations.AddField(
            model_name='parentstudentrelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='students',
            field=models.ManyToManyField(help_text='Students linked to this parent', related_name='parents', through='parent.ParentStudentRelationship', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelationship',
            unique_together={('parent', 'student')},
        ),
    ]
