# Generated by Django 5.2.1 on 2025-10-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1)),
                ('time_in', models.TimeField(blank=True, help_text='Time when student/teacher arrived', null=True)),
                ('time_out', models.TimeField(blank=True, help_text='Time when student/teacher left', null=True)),
            ],
        ),
    ]
