# Generated by Django 5.2.1 on 2025-07-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'student', 'section')},
        ),
    ]
