# Generated by Django 5.2.1 on 2025-08-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_initial'),
        ('teacher', '0006_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.teacher'),
        ),
    ]
