# Generated by Django 5.2.1 on 2025-08-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, help_text='Time when student/teacher arrived', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, help_text='Time when student/teacher left', null=True),
        ),
    ]
