from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register the viewset
router = DefaultRouter()
router.register(r"profiles", views.UserProfileViewSet, basename="userprofile")

# Custom URL patterns for additional endpoints
urlpatterns = [
    # Include the router URLs
    path("", include(router.urls)),
    # Custom endpoints (these will be available through the viewset actions)
    # But you can also create dedicated URL patterns if needed
    # Profile management endpoints
    path("me/", views.UserProfileViewSet.as_view({"get": "me"}), name="profile-me"),
    path(
        "full-profile/",
        views.UserProfileViewSet.as_view({"get": "full_profile"}),
        name="profile-full",
    ),
    path(
        "summary/",
        views.UserProfileViewSet.as_view({"get": "summary"}),
        name="profile-summary",
    ),
    # Profile update endpoints
    path(
        "update-preferences/",
        views.UserProfileViewSet.as_view({"patch": "update_preferences"}),
        name="profile-update-preferences",
    ),
    path(
        "upload-picture/",
        views.UserProfileViewSet.as_view({"post": "upload_profile_picture"}),
        name="profile-upload-picture",
    ),
    # Information endpoints
    path(
        "verification-status/",
        views.UserProfileViewSet.as_view({"get": "verification_status"}),
        name="profile-verification-status",
    ),
    path(
        "contact-info/",
        views.UserProfileViewSet.as_view({"get": "contact_info"}),
        name="profile-contact-info",
    ),
]

# Alternative URL patterns using path parameters
urlpatterns += [
    # Public profile view by username (if you want to implement this)
    # path('public/<str:username>/', views.PublicProfileView.as_view(), name='public-profile'),
    # Profile by user ID (for admin/teacher access)
    # path('user/<int:user_id>/', views.ProfileByUserView.as_view(), name='profile-by-user'),
]

# The router will automatically generate these URLs:
# GET    /api/userprofile/profiles/          - List profiles (filtered to user's own)
# POST   /api/userprofile/profiles/          - Create profile
# GET    /api/userprofile/profiles/{id}/     - Retrieve specific profile
# PUT    /api/userprofile/profiles/{id}/     - Update profile
# PATCH  /api/userprofile/profiles/{id}/     - Partial update profile
# DELETE /api/userprofile/profiles/{id}/     - Delete profile (returns 403)

# Custom action URLs (automatically generated by the router):
# GET    /api/userprofile/profiles/me/                    - Get current user's profile
# GET    /api/userprofile/profiles/full_profile/         - Get complete profile data
# GET    /api/userprofile/profiles/summary/              - Get profile summary
# GET    /api/userprofile/profiles/verification_status/  - Get verification status
# GET    /api/userprofile/profiles/contact_info/         - Get contact information
# PATCH  /api/userprofile/profiles/update_preferences/   - Update preferences
# POST   /api/userprofile/profiles/upload_profile_picture/ - Upload profile picture

app_name = "userprofile"
