# Generated by Django 5.2.1 on 2025-10-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='academic_year',
            new_name='academic_session',
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together={('teacher', 'day_of_week', 'start_time', 'end_time', 'academic_session', 'term')},
        ),
    ]
