# Generated by Django 5.2.1 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_type',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('non-teaching', 'Non-Teaching')], default='teaching', max_length=20),
        ),
    ]
