# Generated by Django 5.2.1 on 2025-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.URLField(blank=True, help_text='Profile picture URL', null=True),
        ),
    ]
