# Generated by Django 5.2.1 on 2025-08-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_assignmentrequest_teacherschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAssignment',
        ),
    ]
