# Generated by Django 5.2.1 on 2025-10-07 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Holiday',
                'verbose_name_plural': 'School Holidays',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(default='School Name', max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('school_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_motto', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.URLField(blank=True, help_text='School logo (Cloudinary URL)', max_length=500, null=True)),
                ('favicon', models.URLField(blank=True, help_text='School favicon (Cloudinary URL)', max_length=500, null=True)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#6366F1', max_length=7)),
                ('typography', models.CharField(default='Inter', max_length=50)),
                ('allow_self_registration', models.BooleanField(default=True)),
                ('email_verification_required', models.BooleanField(default=True)),
                ('registration_approval_required', models.BooleanField(default=False)),
                ('default_user_role', models.CharField(default='student', max_length=20)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_reset_interval', models.IntegerField(default=90)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_symbols', models.BooleanField(default=False)),
                ('password_require_uppercase', models.BooleanField(default=False)),
                ('allow_profile_image_upload', models.BooleanField(default=True)),
                ('profile_image_max_size', models.IntegerField(default=2)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='24-hour', max_length=10)),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brevo_api_key', models.CharField(blank=True, help_text='Brevo API key for email delivery', max_length=255, null=True)),
                ('brevo_sender_email', models.EmailField(blank=True, help_text='Default sender email address', max_length=254, null=True)),
                ('brevo_sender_name', models.CharField(blank=True, help_text='Default sender name', max_length=100, null=True)),
                ('brevo_test_mode', models.BooleanField(default=True, help_text='Enable test mode to prevent actual email sending')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Twilio Account SID', max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Twilio Auth Token', max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Twilio phone number for sending SMS', max_length=20, null=True)),
                ('twilio_test_mode', models.BooleanField(default=True, help_text='Enable test mode to prevent actual SMS sending')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('in_app_notifications_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency for digest notifications', max_length=20)),
                ('brevo_configured', models.BooleanField(default=False, help_text='Brevo is properly configured')),
                ('twilio_configured', models.BooleanField(default=False, help_text='Twilio is properly configured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Setting',
                'verbose_name_plural': 'Communication Settings',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('attendance', 'Attendance'), ('results', 'Results'), ('exams', 'Exams'), ('messaging', 'Messaging'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings'), ('announcements', 'Announcements'), ('events', 'Events'), ('library', 'Library'), ('timetable', 'Timetable'), ('subjects', 'Subjects'), ('classes', 'Classes')], max_length=20)),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('admin', 'Admin')], max_length=10)),
                ('section', models.CharField(choices=[('all', 'All Sections'), ('primary', 'Primary Section'), ('secondary', 'Secondary Section'), ('nursery', 'Nursery Section')], default='all', max_length=15)),
                ('granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'permission_type', 'section'],
                'unique_together': {('module', 'permission_type', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for role display', max_length=7)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('primary_section_access', models.BooleanField(default=True)),
                ('secondary_section_access', models.BooleanField(default=True)),
                ('nursery_section_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='schoolSettings.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('event', 'Event'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('target_audience', models.JSONField(default=list, help_text='List of user types to target')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Announcement',
                'verbose_name_plural': 'School Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_section_access', models.BooleanField(default=True)),
                ('secondary_section_access', models.BooleanField(default=True)),
                ('nursery_section_access', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='user_role_assignments', to='schoolSettings.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='schoolSettings.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
