# Generated by Django 5.2.1 on 2025-07-31 16:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Holiday',
                'verbose_name_plural': 'School Holidays',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system', models.CharField(choices=[('percentage', 'Percentage'), ('letter', 'Letter Grade'), ('gpa', 'GPA')], default='percentage', max_length=20)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('max_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_special', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Preference',
                'verbose_name_plural': 'System Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('academic_updates', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('fee_reminders', models.BooleanField(default=True)),
                ('exam_notifications', models.BooleanField(default=True)),
                ('general_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'unique_together': {('user_type',)},
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('event', 'Event'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('target_audience', models.JSONField(default=list, help_text='List of user types to target')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Announcement',
                'verbose_name_plural': 'School Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(default='Gods Treasure Schools', max_length=200)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('school_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_website', models.URLField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('current_term', models.CharField(default='First Term', max_length=20)),
                ('school_motto', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='12', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school_favicons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])])),
                ('auto_save', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
