# Generated by Django 5.2.1 on 2025-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='animations_enabled',
            field=models.BooleanField(default=True, help_text='Enable smooth transitions and animations'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='border_radius',
            field=models.CharField(choices=[('rounded-none', 'Sharp'), ('rounded', 'Slightly Rounded'), ('rounded-lg', 'Rounded'), ('rounded-xl', 'More Rounded'), ('rounded-2xl', 'Very Rounded')], default='rounded-lg', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='compact_mode',
            field=models.BooleanField(default=False, help_text='Reduce spacing for more content density'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Primary color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='shadow_style',
            field=models.CharField(choices=[('shadow-none', 'No Shadow'), ('shadow-sm', 'Subtle Shadow'), ('shadow-md', 'Medium Shadow'), ('shadow-lg', 'Large Shadow'), ('shadow-xl', 'Extra Large Shadow')], default='shadow-md', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('vibrant', 'Vibrant'), ('minimal', 'Minimal'), ('corporate', 'Corporate')], default='modern', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='typography',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Inter', max_length=50),
        ),
    ]
