# Generated by Django 5.2.1 on 2025-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='site_name',
        ),
    ]
