# Generated by Django 5.2.1 on 2025-08-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0002_schoolsettings_animations_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('vibrant', 'Vibrant'), ('minimal', 'Minimal'), ('corporate', 'Corporate'), ('premium', 'Premium')], default='modern', max_length=20),
        ),
    ]
