# Generated by Django 5.2.1 on 2025-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0002_remove_schoolsettings_site_name'),
    ]

    operations = [
    ]
