# Generated by Django 5.2.1 on 2025-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0003_auto_20251007_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
