# Generated by Django 5.2.1 on 2025-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0003_alter_schoolsettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('modern', 'Modern'), ('classic', 'Classic'), ('vibrant', 'Vibrant'), ('minimal', 'Minimal'), ('corporate', 'Corporate'), ('premium', 'Premium')], default='default', max_length=20),
        ),
    ]
