# Generated by Django 5.2.1 on 2025-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0004_schoolsettings_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='academic_year_end',
        ),
        migrations.RemoveField(
            model_name='schoolsettings',
            name='academic_year_start',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
