# Generated by Django 5.2.1 on 2025-08-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0004_alter_schoolsettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('modern', 'Modern'), ('classic', 'Classic'), ('vibrant', 'Vibrant'), ('minimal', 'Minimal'), ('corporate', 'Corporate'), ('premium', 'Premium'), ('obsidian', 'Obsidian (Ultra Premium)'), ('aurora', 'Aurora (Ultra Premium)'), ('midnight', 'Midnight (Ultra Premium)'), ('crimson', 'Crimson (Ultra Premium)'), ('forest', 'Forest (Ultra Premium)'), ('golden', 'Golden (Ultra Premium)')], default='default', max_length=20),
        ),
    ]
