# Generated by Django 5.2.1 on 2025-08-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0005_alter_schoolsettings_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brevo_api_key', models.CharField(blank=True, help_text='Brevo API key for email delivery', max_length=255, null=True)),
                ('brevo_sender_email', models.EmailField(blank=True, help_text='Default sender email address', max_length=254, null=True)),
                ('brevo_sender_name', models.CharField(blank=True, help_text='Default sender name', max_length=100, null=True)),
                ('brevo_test_mode', models.BooleanField(default=True, help_text='Enable test mode to prevent actual email sending')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Twilio Account SID', max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Twilio Auth Token', max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Twilio phone number for sending SMS', max_length=20, null=True)),
                ('twilio_test_mode', models.BooleanField(default=True, help_text='Enable test mode to prevent actual SMS sending')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('sms_notifications_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('in_app_notifications_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency for digest notifications', max_length=20)),
                ('brevo_configured', models.BooleanField(default=False, help_text='Brevo is properly configured')),
                ('twilio_configured', models.BooleanField(default=False, help_text='Twilio is properly configured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Setting',
                'verbose_name_plural': 'Communication Settings',
            },
        ),
    ]
