# Generated by Django 5.2.1 on 2025-10-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0005_remove_schoolsettings_academic_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='secondary_color',
        ),
    ]
