# Generated by Django 5.2.1 on 2025-08-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0006_communicationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('attendance', 'Attendance'), ('results', 'Results'), ('exams', 'Exams'), ('messaging', 'Messaging'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings'), ('announcements', 'Announcements'), ('events', 'Events'), ('library', 'Library'), ('timetable', 'Timetable'), ('subjects', 'Subjects'), ('classes', 'Classes')], max_length=20)),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('admin', 'Admin')], max_length=10)),
                ('section', models.CharField(choices=[('all', 'All Sections'), ('primary', 'Primary Section'), ('secondary', 'Secondary Section'), ('nursery', 'Nursery Section')], default='all', max_length=15)),
                ('granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'permission_type', 'section'],
                'unique_together': {('module', 'permission_type', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for role display', max_length=7)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('primary_section_access', models.BooleanField(default=True)),
                ('secondary_section_access', models.BooleanField(default=True)),
                ('nursery_section_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='schoolSettings.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_section_access', models.BooleanField(default=True)),
                ('secondary_section_access', models.BooleanField(default=True)),
                ('nursery_section_access', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='user_role_assignments', to='schoolSettings.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='schoolSettings.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
