# Generated by Django 5.2.1 on 2025-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0006_remove_schoolsettings_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
    ]
