# Generated by Django 5.2.1 on 2025-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0007_permission_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='parent_portal_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable parent portal access'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='student_portal_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable student portal access'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='teacher_portal_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable teacher portal access'),
        ),
    ]
