# Generated by Django 5.2.1 on 2025-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0007_schoolsettings_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
