# Generated by Django 5.2.1 on 2025-10-07 18:18

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0009_remove_schoolsettings_secondary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="allow_self_registration",
            field=models.BooleanField(default=False),
        ),
    ]
