# Generated by Django 5.2.1 on 2025-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0010_add_allow_self_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='allow_self_registration',
            field=models.BooleanField(default=True),
        ),
    ]
