# Generated by Django 5.2.1 on 2025-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0012_add_email_verification_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="registration_approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="default_user_role",
            field=models.CharField(max_length=50, default="student"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="password_min_length",
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="password_reset_interval",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="password_require_numbers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="password_require_symbols",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="password_require_uppercase",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="allow_profile_image_upload",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="profile_image_max_size",
            field=models.IntegerField(default=5),  # size in MB
        ),
    ]
