# Generated by Django 5.2.1 on 2025-10-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0013_add_missing_fields_to_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='default_user_role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='password_require_symbols',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='password_require_uppercase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='password_reset_interval',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='profile_image_max_size',
            field=models.IntegerField(default=2),
        ),
    ]
