# Generated by Django 5.2.1 on 2025-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0014_alter_schoolsettings_default_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='current_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
