# Generated by Django 5.2.1 on 2025-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0015_schoolsettings_current_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='account_lock_duration',
            field=models.IntegerField(default=15, help_text='Account lock duration in minutes after failed login attempts'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5, help_text='Maximum login attempts before account lock'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='password_expiration',
            field=models.IntegerField(default=90, help_text='Password expiration period in days'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='session_timeout',
            field=models.IntegerField(default=30, help_text='Session timeout in minutes'),
        ),
    ]
