# Generated by Django 5.2.1 on 2025-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolSettings', '0017_fix_password_expiration_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='parent_portal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='student_portal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='teacher_portal_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
