# Generated by Django 5.2.1 on 2025-10-27 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='The admin this user reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], help_text='School section (Nursery/Primary/Junior Secondary/Senior Secondary)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('senior_secondary_admin', 'Senior Secondary Admin'), ('junior_secondary_admin', 'Junior Secondary Admin'), ('primary_admin', 'Primary Admin'), ('nursery_admin', 'Nursery Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=30),
        ),
    ]
