# Generated by Django 5.2.1 on 2025-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reports_to_customuser_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('secondary_admin', 'Secondary Admin'), ('senior_secondary_admin', 'Senior Secondary Admin'), ('junior_secondary_admin', 'Junior Secondary Admin'), ('primary_admin', 'Primary Admin'), ('nursery_admin', 'Nursery Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], help_text='School section (Nursery/Primary/Junior Secondary/Senior Secondary)', max_length=20, null=True),
        ),
    ]
