# Generated by Django 5.2.1 on 2025-11-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schoolSettings", "0002_sync_model"),
        ("users", "0003_alter_customuser_role_alter_customuser_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School this user belongs to (required for multi-tenant isolation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="schoolSettings.schoolsettings",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["school", "role"], name="users_custo_school__bdc208_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["school", "section"], name="users_custo_school__2371f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["school", "is_active"], name="users_custo_school__e7ca8f_idx"
            ),
        ),
    ]
